runtime: php
env: flex

runtime_config:
  document_root: public

handlers:
- url: /index\.php
  script: auto

- url: /(.+)
  static_files: public/\1
  upload: public/(.+)

- url: /.*
  script: auto

env_variables:
  CLOUD_SQL_CONNECTION_NAME: "balmy-doodad-386421:europe-west1:bd-electricidadfcv"
  DB_USER: "fundeanu"
  DB_PASSWORD: "password1234"
  DB_NAME: "electricidadfcv"
