runtime: php
env: flex

runtime_config:
  document_root: public

handlers:
- url: /index\.php
  script: auto

- url: /(.+)
  static_files: public/\1
  upload: public/(.+)

- url: /.*
  script: auto

- beta_settings:
  cloud_sql_instances: balmy-doodad-386421:europe-west1:bd-electricidadfcv
