name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.3
      with:
        version: '349.0.0'
        project_id: balmy-doodad-386421

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
